import { BoxUnit } from '@/types/box';

export const INITIAL_BOX_UNITS: BoxUnit[] = [
  {
    id: 'box-1',
    boxId: 'MyBox-123456',
    serialNumber: 'B2B-LKR-9821-X',
    name: 'Thomas Estate Smart Hub',
    address: 'Plot 12, Thomas Estate, Ajah',
    city: 'Ajah, Lagos',
    state: 'Lagos',
    latitude: 6.4674,
    longitude: 3.5852,
    ownerId: 'u-2',
    ownerName: 'Babatunde Nnamani',
    ownerEmail: 'babatunde@box2box.ng',
    ownerPhone: '+234 803 456 7890',
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&auto=format&fit=crop&q=80',
    model: '4 Cabinets',
    status: 'Activated',
    batteryHealth: {
      status: 'Excellent',
      percentage: 95,
      voltage: '12.6V',
      isCharging: true,
    },
    iotStatus: {
      isOnline: true,
      signalStrength: 'Strong',
      firmwareVersion: 'v2.4.1-rc3',
      temperature: '22.4°C',
      humidity: '48%',
      lastPing: 'Just now (12s ago)',
    },
    usageRate: '91%',
    rating: 5.0,
    totalBookings: 1420,
    dateInstalled: 'Jan 15, 2025',
    compartments: [
      {
        id: 'comp-1-1',
        compartmentNumber: 1,
        label: 'A1 - Top Left',
        size: 'Medium',
        status: 'Occupied',
        currentBookingId: 'BK-89021',
        currentCustomerName: 'Aku Cynthia',
        currentCustomerPhone: '+234 812 345 6789',
        trackingNumber: 'TRK-LG-982194',
        parcelDescription: 'Electronics & Mac Accessories',
        isLocked: true,
        isDoorClosed: true,
        lastOpenedAt: 'Today, 09:15 AM',
      },
      {
        id: 'comp-1-2',
        compartmentNumber: 2,
        label: 'A2 - Top Right',
        size: 'Large',
        status: 'Available',
        isLocked: true,
        isDoorClosed: true,
        lastOpenedAt: 'Yesterday, 04:30 PM',
      },
      {
        id: 'comp-1-3',
        compartmentNumber: 3,
        label: 'B1 - Bottom Left',
        size: 'Medium',
        status: 'Occupied',
        currentBookingId: 'BK-89035',
        currentCustomerName: 'David Adeleke',
        currentCustomerPhone: '+234 809 111 2233',
        trackingNumber: 'TRK-LG-771239',
        parcelDescription: 'Official Documents & Seal',
        isLocked: true,
        isDoorClosed: true,
        lastOpenedAt: 'Today, 10:45 AM',
      },
      {
        id: 'comp-1-4',
        compartmentNumber: 4,
        label: 'B2 - Bottom Right',
        size: 'Extra Large',
        status: 'Reserved',
        currentBookingId: 'BK-89090',
        currentCustomerName: 'Maryam Bello',
        currentCustomerPhone: '+234 818 990 0112',
        trackingNumber: 'TRK-LG-334190',
        parcelDescription: 'Pending Courier Dropoff',
        isLocked: true,
        isDoorClosed: true,
        lastOpenedAt: '2 days ago',
      },
    ],
    eventLogs: [
      {
        id: 'ev-1',
        timestamp: '10:45 AM',
        eventType: 'dropoff',
        title: 'Courier Dropoff Confirmed',
        description: 'Rider Chinedu O. deposited package TRK-LG-771239 via OTP verification.',
        compartmentLabel: 'B1 - Bottom Left',
        actor: 'Rider Chinedu O.',
        severity: 'normal',
      },
      {
        id: 'ev-2',
        timestamp: '09:15 AM',
        eventType: 'unlock',
        title: 'Customer Self-Pickup',
        description: 'Customer Aku Cynthia unlocked compartment via mobile app token.',
        compartmentLabel: 'A1 - Top Left',
        actor: 'Aku Cynthia',
        severity: 'normal',
      },
      {
        id: 'ev-3',
        timestamp: 'Yesterday 08:30 PM',
        eventType: 'power_event',
        title: 'Solar Backup Active',
        description: 'Main AC switched to auxiliary solar battery circuit (96% charged).',
        actor: 'System Sensor',
        severity: 'normal',
      },
    ],
  },
  {
    id: 'box-2',
    boxId: 'MyBox-123457',
    serialNumber: 'B2B-LKR-9822-Y',
    name: 'Admiralty Way Hub',
    address: 'Admiralty Way, Lekki Phase 1',
    city: 'Lekki, Lagos',
    state: 'Lagos',
    latitude: 6.4485,
    longitude: 3.4723,
    ownerId: 'u-7',
    ownerName: 'Folake Solanke',
    ownerEmail: 'folake.s@box2box.ng',
    ownerPhone: '+234 802 334 5566',
    ownerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&auto=format&fit=crop&q=80',
    model: '4 Cabinets',
    status: 'Disabled',
    batteryHealth: {
      status: 'Good',
      percentage: 75,
      voltage: '12.1V',
      isCharging: false,
    },
    iotStatus: {
      isOnline: false,
      signalStrength: 'Offline',
      firmwareVersion: 'v2.3.8',
      temperature: '28.1°C',
      humidity: '62%',
      lastPing: '4 hours ago',
    },
    usageRate: '5%',
    rating: 0.9,
    totalBookings: 89,
    dateInstalled: 'Feb 10, 2025',
    compartments: [
      {
        id: 'comp-2-1',
        compartmentNumber: 1,
        label: 'A1',
        size: 'Medium',
        status: 'Maintenance',
        isLocked: true,
        isDoorClosed: true,
        lastOpenedAt: '3 days ago',
      },
      {
        id: 'comp-2-2',
        compartmentNumber: 2,
        label: 'A2',
        size: 'Large',
        status: 'Maintenance',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-2-3',
        compartmentNumber: 3,
        label: 'B1',
        size: 'Medium',
        status: 'Maintenance',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-2-4',
        compartmentNumber: 4,
        label: 'B2',
        size: 'Large',
        status: 'Maintenance',
        isLocked: true,
        isDoorClosed: true,
      },
    ],
    eventLogs: [
      {
        id: 'ev-201',
        timestamp: '4 hours ago',
        eventType: 'tamper_alert',
        title: 'Communication Heartbeat Timeout',
        description: 'Gateway lost 4G connection. Unit auto-disabled for security protocols.',
        actor: 'Box Watchdog',
        severity: 'critical',
      },
    ],
  },
  {
    id: 'box-3',
    boxId: 'MyBox-123458',
    serialNumber: 'B2B-LKR-9823-Z',
    name: 'Wuse II Central Vault',
    address: 'Aminu Kano Crescent, Wuse II',
    city: 'Wuse II, Abuja',
    state: 'Abuja',
    latitude: 9.0765,
    longitude: 7.4764,
    ownerId: 'u-8',
    ownerName: 'Emeka Eze',
    ownerEmail: 'emeka.eze@box2box.ng',
    ownerPhone: '+234 805 778 9900',
    ownerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&auto=format&fit=crop&q=80',
    model: '4 Cabinets',
    status: 'Activated',
    batteryHealth: {
      status: 'Fair',
      percentage: 45,
      voltage: '11.8V',
      isCharging: false,
    },
    iotStatus: {
      isOnline: true,
      signalStrength: 'Moderate',
      firmwareVersion: 'v2.4.1-rc3',
      temperature: '24.2°C',
      humidity: '40%',
      lastPing: '2 mins ago',
    },
    usageRate: '78%',
    rating: 4.8,
    totalBookings: 980,
    dateInstalled: 'Mar 01, 2025',
    compartments: [
      {
        id: 'comp-3-1',
        compartmentNumber: 1,
        label: 'A1 - Upper',
        size: 'Medium',
        status: 'Occupied',
        currentBookingId: 'BK-77412',
        currentCustomerName: 'Hadiza Musa',
        currentCustomerPhone: '+234 814 223 3445',
        trackingNumber: 'TRK-AB-889012',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-3-2',
        compartmentNumber: 2,
        label: 'A2 - Upper',
        size: 'Large',
        status: 'Occupied',
        currentBookingId: 'BK-77419',
        currentCustomerName: 'Kenechukwu Ani',
        currentCustomerPhone: '+234 803 999 1122',
        trackingNumber: 'TRK-AB-889020',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-3-3',
        compartmentNumber: 3,
        label: 'B1 - Lower',
        size: 'Medium',
        status: 'Available',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-3-4',
        compartmentNumber: 4,
        label: 'B2 - Lower',
        size: 'Extra Large',
        status: 'Available',
        isLocked: true,
        isDoorClosed: true,
      },
    ],
    eventLogs: [
      {
        id: 'ev-301',
        timestamp: 'Today, 11:20 AM',
        eventType: 'dropoff',
        title: 'Package Deposited',
        description: 'Locker B2 was reserved and parcel loaded successfully.',
        actor: 'Courier DHL Express',
        severity: 'normal',
      },
    ],
  },
  {
    id: 'box-4',
    boxId: 'MyBox-123459',
    serialNumber: 'B2B-LKR-9824-A',
    name: 'Ring Road Commercial Hub',
    address: 'Ring Road, by Challenge Junction',
    city: 'Ibadan',
    state: 'Oyo',
    latitude: 7.3775,
    longitude: 3.947,
    ownerId: 'u-9',
    ownerName: 'Chukwuemeka Obi',
    ownerEmail: 'c.obi@box2box.ng',
    ownerPhone: '+234 807 665 4433',
    ownerAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=80&auto=format&fit=crop&q=80',
    model: '4 Cabinets',
    status: 'Maintenance',
    batteryHealth: {
      status: 'Critical',
      percentage: 15,
      voltage: '10.9V',
      isCharging: false,
    },
    iotStatus: {
      isOnline: true,
      signalStrength: 'Weak',
      firmwareVersion: 'v2.3.9',
      temperature: '31.5°C',
      humidity: '55%',
      lastPing: '15 mins ago',
    },
    usageRate: '100%',
    rating: 1.2,
    totalBookings: 610,
    dateInstalled: 'Apr 11, 2025',
    compartments: [
      {
        id: 'comp-4-1',
        compartmentNumber: 1,
        label: 'A1',
        size: 'Medium',
        status: 'Maintenance',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-4-2',
        compartmentNumber: 2,
        label: 'A2',
        size: 'Large',
        status: 'Maintenance',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-4-3',
        compartmentNumber: 3,
        label: 'B1',
        size: 'Medium',
        status: 'Maintenance',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-4-4',
        compartmentNumber: 4,
        label: 'B2',
        size: 'Large',
        status: 'Maintenance',
        isLocked: true,
        isDoorClosed: true,
      },
    ],
    eventLogs: [
      {
        id: 'ev-401',
        timestamp: '1 hour ago',
        eventType: 'power_event',
        title: 'Critical Battery Level Warning (< 15%)',
        description: 'Battery voltage dropped below 11.0V. Technician dispatch requested.',
        actor: 'BMS Telemetry',
        severity: 'critical',
      },
    ],
  },
  {
    id: 'box-5',
    boxId: 'MyBox-123460',
    serialNumber: 'B2B-LKR-9825-B',
    name: 'Old GRA River Hub',
    address: 'Forces Avenue, Old GRA',
    city: 'Port Harcourt',
    state: 'Rivers',
    latitude: 4.8156,
    longitude: 7.0498,
    ownerId: 'u-10',
    ownerName: 'Damilola Ajayi',
    ownerEmail: 'dami.ajayi@box2box.ng',
    ownerPhone: '+234 813 889 0011',
    ownerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&auto=format&fit=crop&q=80',
    model: '4 Cabinets',
    status: 'Activated',
    batteryHealth: {
      status: 'Excellent',
      percentage: 98,
      voltage: '12.8V',
      isCharging: true,
    },
    iotStatus: {
      isOnline: true,
      signalStrength: 'Strong',
      firmwareVersion: 'v2.4.1-rc3',
      temperature: '23.0°C',
      humidity: '52%',
      lastPing: '1 min ago',
    },
    usageRate: '86%',
    rating: 5.0,
    totalBookings: 1890,
    dateInstalled: 'May 05, 2025',
    compartments: [
      {
        id: 'comp-5-1',
        compartmentNumber: 1,
        label: 'A1',
        size: 'Medium',
        status: 'Occupied',
        currentBookingId: 'BK-55201',
        currentCustomerName: 'Somi Briggs',
        currentCustomerPhone: '+234 809 332 1199',
        trackingNumber: 'TRK-PH-9921',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-5-2',
        compartmentNumber: 2,
        label: 'A2',
        size: 'Large',
        status: 'Available',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-5-3',
        compartmentNumber: 3,
        label: 'B1',
        size: 'Medium',
        status: 'Occupied',
        currentBookingId: 'BK-55209',
        currentCustomerName: 'Tamuno George',
        currentCustomerPhone: '+234 802 771 9900',
        trackingNumber: 'TRK-PH-9934',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-5-4',
        compartmentNumber: 4,
        label: 'B2',
        size: 'Extra Large',
        status: 'Available',
        isLocked: true,
        isDoorClosed: true,
      },
    ],
    eventLogs: [
      {
        id: 'ev-501',
        timestamp: 'Today, 07:45 AM',
        eventType: 'unlock',
        title: 'Morning Automated Health Check',
        description: 'Self-test completed. Solenoid door latches passed 100%.',
        actor: 'Self Test Daemon',
        severity: 'normal',
      },
    ],
  },
  {
    id: 'box-6',
    boxId: 'MyBox-123461',
    serialNumber: 'B2B-LKR-9826-C',
    name: 'Victoria Island Financial Core',
    address: 'Ahmadu Bello Way, VI',
    city: 'Victoria Island, Lagos',
    state: 'Lagos',
    latitude: 6.4281,
    longitude: 3.4219,
    ownerId: 'u-11',
    ownerName: 'Oluwaseun Balogun',
    ownerEmail: 'seun.b@box2box.ng',
    ownerPhone: '+234 802 884 1290',
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&auto=format&fit=crop&q=80',
    model: '6 Cabinets',
    status: 'Activated',
    batteryHealth: {
      status: 'Excellent',
      percentage: 92,
      voltage: '12.5V',
      isCharging: true,
    },
    iotStatus: {
      isOnline: true,
      signalStrength: 'Strong',
      firmwareVersion: 'v2.4.1-rc3',
      temperature: '21.8°C',
      humidity: '44%',
      lastPing: '30s ago',
    },
    usageRate: '94%',
    rating: 4.9,
    totalBookings: 2150,
    dateInstalled: 'Jan 28, 2025',
    compartments: [
      {
        id: 'comp-6-1',
        compartmentNumber: 1,
        label: 'A1',
        size: 'Medium',
        status: 'Occupied',
        currentBookingId: 'BK-10492',
        currentCustomerName: 'Zenith Securities Desk',
        trackingNumber: 'TRK-VI-1011',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-6-2',
        compartmentNumber: 2,
        label: 'A2',
        size: 'Medium',
        status: 'Occupied',
        currentBookingId: 'BK-10495',
        currentCustomerName: 'Access Vault Dispatch',
        trackingNumber: 'TRK-VI-1022',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-6-3',
        compartmentNumber: 3,
        label: 'B1',
        size: 'Large',
        status: 'Available',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-6-4',
        compartmentNumber: 4,
        label: 'B2',
        size: 'Large',
        status: 'Occupied',
        currentBookingId: 'BK-10498',
        currentCustomerName: 'Techpoint Media',
        trackingNumber: 'TRK-VI-1033',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-6-5',
        compartmentNumber: 5,
        label: 'C1',
        size: 'Extra Large',
        status: 'Occupied',
        currentBookingId: 'BK-10501',
        currentCustomerName: 'FBN Quest',
        trackingNumber: 'TRK-VI-1044',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-6-6',
        compartmentNumber: 6,
        label: 'C2',
        size: 'Extra Large',
        status: 'Available',
        isLocked: true,
        isDoorClosed: true,
      },
    ],
    eventLogs: [
      {
        id: 'ev-601',
        timestamp: '15 mins ago',
        eventType: 'dropoff',
        title: 'VIP Delivery Intake',
        description: 'Secured courier delivered confidential parcel TRK-VI-1044.',
        actor: 'Rider Segun A.',
        severity: 'normal',
      },
    ],
  },
  {
    id: 'box-7',
    boxId: 'MyBox-123462',
    serialNumber: 'B2B-LKR-9827-D',
    name: 'Independence Layout Hub',
    address: 'Plot 44, Independence Layout',
    city: 'Enugu',
    state: 'Enugu',
    latitude: 6.4584,
    longitude: 7.5464,
    ownerId: 'u-12',
    ownerName: 'Ngozi Okonjo',
    ownerEmail: 'ngozi.o@logistics.ng',
    ownerPhone: '+234 816 778 8899',
    ownerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&auto=format&fit=crop&q=80',
    model: '4 Cabinets',
    status: 'Activated',
    batteryHealth: {
      status: 'Good',
      percentage: 82,
      voltage: '12.3V',
      isCharging: true,
    },
    iotStatus: {
      isOnline: true,
      signalStrength: 'Strong',
      firmwareVersion: 'v2.4.1-rc3',
      temperature: '25.0°C',
      humidity: '45%',
      lastPing: '5 mins ago',
    },
    usageRate: '68%',
    rating: 4.7,
    totalBookings: 720,
    dateInstalled: 'Jun 19, 2025',
    compartments: [
      {
        id: 'comp-7-1',
        compartmentNumber: 1,
        label: 'A1',
        size: 'Medium',
        status: 'Available',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-7-2',
        compartmentNumber: 2,
        label: 'A2',
        size: 'Large',
        status: 'Occupied',
        currentBookingId: 'BK-7012',
        currentCustomerName: 'Obinna Igwe',
        trackingNumber: 'TRK-EN-701',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-7-3',
        compartmentNumber: 3,
        label: 'B1',
        size: 'Medium',
        status: 'Available',
        isLocked: true,
        isDoorClosed: true,
      },
      {
        id: 'comp-7-4',
        compartmentNumber: 4,
        label: 'B2',
        size: 'Extra Large',
        status: 'Occupied',
        currentBookingId: 'BK-7015',
        currentCustomerName: 'Adaeze Nwosu',
        trackingNumber: 'TRK-EN-705',
        isLocked: true,
        isDoorClosed: true,
      },
    ],
    eventLogs: [
      {
        id: 'ev-701',
        timestamp: 'Today, 08:12 AM',
        eventType: 'pickup',
        title: 'Customer Locker Pickup',
        description: 'Code validated. Door A2 unlocked and re-latched.',
        actor: 'Obinna Igwe',
        severity: 'normal',
      },
    ],
  },
];
