import {
  StatItem,
  NewUserRow,
  RecentBoxRow,
  InventoryRow,
  ReportItem,
  FlagTriggerItem,
  BookingItem,
  ActiveDeliveryItem,
} from '@/types/dashboard';

export const STATS_DATA: StatItem[] = [
  {
    id: 'users',
    title: 'Users',
    value: '200,000,000',
    change: '+4% today',
    subtext: 'Box owners, riders...',
    isPositive: true,
  },
  {
    id: 'active_boxes',
    title: 'Active boxes',
    value: '7,935',
    change: '+12% today',
    subtext: '320 Cities',
    isPositive: true,
  },
  {
    id: 'active_deliveries',
    title: 'Active Deliveries',
    value: '6,000,000',
    change: 'Ongoing',
    subtext: 'Live in-transit deliveries',
    isPositive: true,
  },
  {
    id: 'cities',
    title: 'Cities',
    value: '42',
    change: '+4% today',
    subtext: 'Serviced locations',
    isPositive: true,
  },
  {
    id: 'revenue',
    title: 'Revenue',
    value: '₦79,860,900',
    change: '+4% today',
    subtext: 'Booking commission',
    isPositive: true,
  },
  {
    id: 'avg_time',
    title: 'Avg. del time',
    value: '3mins',
    change: '+4% today',
    subtext: 'Pickup - drop off',
    isPositive: true,
  },
];

export const NEW_USERS_DATA: NewUserRow[] = [
  {
    id: 'u-1',
    name: 'Akunwanne Nwachukwu',
    email: 'akuns@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&auto=format&fit=crop&q=80',
    location: 'Awka, Anambra, Nigeria',
    dateJoined: 'May 02, 2025',
    userType: 'Customer',
  },
  {
    id: 'u-2',
    name: 'Babatunde Nnamani',
    email: 'babatunde.n@box2box.ng',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&auto=format&fit=crop&q=80',
    location: 'Ajah, Lagos, Nigeria',
    dateJoined: 'May 02, 2025',
    userType: 'Box owner',
  },
  {
    id: 'u-3',
    name: 'Chioma Adeleke',
    email: 'chioma.a@delivery.ng',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&auto=format&fit=crop&q=80',
    location: 'Ikeja, Lagos, Nigeria',
    dateJoined: 'May 02, 2025',
    userType: 'Customer',
  },
  {
    id: 'u-4',
    name: 'Ibrahim Danjuma',
    email: 'ibrahim.d@rider.ng',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&auto=format&fit=crop&q=80',
    location: 'Garki, Abuja, Nigeria',
    dateJoined: 'May 02, 2025',
    userType: 'Rider',
  },
  {
    id: 'u-5',
    name: 'Ngozi Okonjo',
    email: 'ngozi.o@logistics.ng',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&auto=format&fit=crop&q=80',
    location: 'Enugu, Enugu, Nigeria',
    dateJoined: 'May 02, 2025',
    userType: 'Customer',
  },
];

export const RECENT_BOXES_DATA: RecentBoxRow[] = [
  {
    id: 'box-1',
    boxId: 'MyBox-123456',
    address: 'Thomas Estate, Ajah, Lagos, Nigeria',
    ownerName: 'Babatunde Nnamani',
    ownerEmail: 'babatunde@box2box.ng',
    capacity: '4 Cabinets',
    status: 'Activated',
    batteryHealth: { status: 'Excellent', percentage: 95 },
    usageRate: '91%',
    rating: 5.0,
  },
  {
    id: 'box-2',
    boxId: 'MyBox-123457',
    address: 'Admiralty Way, Lekki Phase 1, Lagos',
    ownerName: 'Folake Solanke',
    ownerEmail: 'folake.s@box2box.ng',
    capacity: '4 Cabinets',
    status: 'Disabled',
    batteryHealth: { status: 'Good', percentage: 75 },
    usageRate: '5%',
    rating: 0.9,
  },
  {
    id: 'box-3',
    boxId: 'MyBox-123458',
    address: 'Wuse 2, Abuja, Nigeria',
    ownerName: 'Emeka Eze',
    ownerEmail: 'emeka.eze@box2box.ng',
    capacity: '4 Cabinets',
    status: 'Activated',
    batteryHealth: { status: 'Fair', percentage: 45 },
    usageRate: '78%',
    rating: 4.8,
  },
  {
    id: 'box-4',
    boxId: 'MyBox-123459',
    address: 'Ring Road, Ibadan, Oyo, Nigeria',
    ownerName: 'Chukwuemeka Obi',
    ownerEmail: 'c.obi@box2box.ng',
    capacity: '4 Cabinets',
    status: 'Disabled',
    batteryHealth: { status: 'Critical', percentage: 15 },
    usageRate: '100%',
    rating: 1.2,
  },
  {
    id: 'box-5',
    boxId: 'MyBox-123460',
    address: 'Old GRA, Port Harcourt, Rivers',
    ownerName: 'Damilola Ajayi',
    ownerEmail: 'dami.ajayi@box2box.ng',
    capacity: '4 Cabinets',
    status: 'Activated',
    batteryHealth: { status: 'Excellent', percentage: 98 },
    usageRate: '86%',
    rating: 5.0,
  },
];

export const INVENTORY_DATA: InventoryRow[] = [
  {
    id: 'inv-1',
    item: 'MyBox-123456',
    type: 'Storage unit',
    modelCategory: '4 Cabinet series',
    quantity: 100,
    lastUpdated: 'March 11, 2024 | 11:00 AM',
    updatedBy: 'Chinwe Eleri',
    status: 'Available',
    location: 'Tangrida, Awka, Nigeria',
  },
  {
    id: 'inv-2',
    item: 'Battery Pack',
    type: 'Accessories',
    modelCategory: 'Main module 48V',
    quantity: 18,
    lastUpdated: 'March 11, 2024 | 11:00 AM',
    updatedBy: 'Chinwe Eleri',
    status: 'In demand',
    location: 'Tangrida, Awka, Nigeria',
  },
  {
    id: 'inv-3',
    item: 'Oak Timber Panels',
    type: 'Material',
    modelCategory: 'Cabinet exterior',
    quantity: 0,
    lastUpdated: 'March 11, 2024 | 11:00 AM',
    updatedBy: 'Chinwe Eleri',
    status: 'Out of stock',
    location: 'Tangrida, Awka, Nigeria',
  },
  {
    id: 'inv-4',
    item: 'MyBox-123456',
    type: 'Storage unit',
    modelCategory: '2 Cabinet series',
    quantity: 70,
    lastUpdated: 'March 11, 2024 | 11:00 AM',
    updatedBy: 'Chinwe Eleri',
    status: 'Available',
    location: 'Tangrida, Awka, Nigeria',
  },
  {
    id: 'inv-5',
    item: 'MyBox-123456',
    type: 'Storage unit',
    modelCategory: '8 Cabinet series',
    quantity: 180,
    lastUpdated: 'March 11, 2024 | 11:00 AM',
    updatedBy: 'Chinwe Eleri',
    status: 'Available',
    location: 'Tangrida, Awka, Nigeria',
  },
];

export const REPORTS_DATA: ReportItem[] = [
  {
    id: 'rep-1',
    title: 'Package Mishandled report',
    description: 'My item was tampered with upon retrieval from the smart unit...',
    reportCode: 'R-123465',
    time: '13:25',
    status: 'Pending',
  },
  {
    id: 'rep-2',
    title: 'Cleanliness report',
    description: 'The cabinet was too dirty with dust inside compartment 2',
    reportCode: 'R-123465',
    time: '13:25',
    status: 'Resolved',
  },
  {
    id: 'rep-3',
    title: 'Theft report',
    description: 'My item is missing from locker bay #4B',
    reportCode: 'R-123465',
    time: '13:25',
    status: 'In progress',
  },
  {
    id: 'rep-4',
    title: 'Payment report',
    description: "My withdrawal hasn't been processed since yesterday",
    reportCode: 'R-123465',
    time: '13:25',
    status: 'Pending',
  },
  {
    id: 'rep-5',
    title: 'Package Mishandled report',
    description: 'Fragile art piece had corner damage during courier handover',
    reportCode: 'R-123465',
    time: '13:25',
    status: 'Pending',
  },
];

export const FLAG_TRIGGERS_DATA: FlagTriggerItem[] = [
  {
    id: 'flag-1',
    title: 'Box forced open',
    boxId: 'MyBox-123456',
    time: '13:25',
    severity: 'Critical',
    actionLabel: 'Disable box',
  },
  {
    id: 'flag-2',
    title: 'Multiple failed access attempt',
    boxId: 'MyBox-123456',
    time: '13:25',
    severity: 'Critical',
    actionLabel: 'Disable box',
  },
  {
    id: 'flag-3',
    title: 'Offline too long',
    boxId: 'MyBox-123456',
    time: '13:25',
    severity: 'Needs review',
    actionLabel: 'Disable box',
  },
  {
    id: 'flag-4',
    title: 'Multiple failed access attempt',
    boxId: 'MyBox-123456',
    time: '13:25',
    severity: 'Critical',
    actionLabel: 'Disable box',
  },
  {
    id: 'flag-5',
    title: 'Box forced open',
    boxId: 'MyBox-123456',
    time: '13:25',
    severity: 'Critical',
    actionLabel: 'Disable box',
  },
];

export const BOOKINGS_DATA: BookingItem[] = [
  { id: 'bk-1', bookingCode: '#BK-123456', boxInfo: 'MyBox-123456 • MyBox123487', time: '13:25' },
  { id: 'bk-2', bookingCode: '#BK-123457', boxInfo: 'MyBox-123456', time: '13:25' },
  { id: 'bk-3', bookingCode: '#BK-123458', boxInfo: 'MyBox-123456', time: '13:25' },
  { id: 'bk-4', bookingCode: '#BK-123459', boxInfo: 'MyBox-123456', time: '13:25' },
];

export const ACTIVE_DELIVERIES_DATA: ActiveDeliveryItem[] = [
  { id: 'del-1', bookingCode: '#BK-123456', statusText: 'Waiting drop off', time: '13:25' },
  { id: 'del-2', bookingCode: '#BK-123457', statusText: 'Pickup confirmed', time: '13:25' },
  { id: 'del-3', bookingCode: '#BK-123458', statusText: 'In transit', time: '13:25' },
  { id: 'del-4', bookingCode: '#BK-123459', statusText: 'Waiting drop off', time: '13:25' },
];
