import { StorageOrder, WarehouseZone, CourierFleet, SmartLockerBank, ActivityEvent } from '@/types';

export const INITIAL_ORDERS: StorageOrder[] = [
  {
    id: 'ord-8921',
    trackingNumber: 'B2B-ES-8921',
    customerName: 'Elena Rostova',
    customerEmail: 'elena.rostova@designstudio.es',
    customerPhone: '+34 612 884 921',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    serviceType: 'door-to-door',
    itemsSummary: '4x Archive Boxes, 2x Mid-Century Chairs, 1x Framed Art Canvas',
    itemsCount: 7,
    volumeM3: 4.8,
    pickupAddress: 'Calle de Serrano 45, 28001 Madrid',
    deliveryAddress: 'Box2Box Hub Central Madrid, Nave 12',
    status: 'stored_in_vault',
    courierAssigned: {
      id: 'cr-01',
      name: 'Diego Morales',
      phone: '+34 689 112 004',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
      vehiclePlate: '9421-MBB',
      vehicleType: 'Electric Van',
    },
    warehouseHub: 'Madrid Central Hub #01',
    warehouseBay: 'Bay B-04 / Rack 2',
    scheduledDate: '2026-09-28',
    createdAt: '2026-09-28T08:15:00Z',
    totalAmount: 189.5,
    paymentStatus: 'paid',
    climateControlled: true,
    qrCodeToken: 'B2B-TOKEN-8921-X99',
  },
  {
    id: 'ord-8922',
    trackingNumber: 'B2B-ES-8922',
    customerName: 'Carlos Mendonça',
    customerEmail: 'carlos.m@techstart.io',
    customerPhone: '+34 675 401 229',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    serviceType: 'door-to-door',
    itemsSummary: '12x Heavy Duty Storage Boxes, Server Racks, 2x Monoblock Desks',
    itemsCount: 15,
    volumeM3: 11.2,
    pickupAddress: 'Paseo de la Castellana 110, Madrid',
    deliveryAddress: 'Box2Box Hub Central Madrid, Nave 14',
    status: 'in_transit',
    courierAssigned: {
      id: 'cr-02',
      name: 'Sofia Alva',
      phone: '+34 622 901 883',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
      vehiclePlate: '4091-KTR',
      vehicleType: 'Sprinter Max',
    },
    warehouseHub: 'Madrid Central Hub #01',
    warehouseBay: 'Bay A-11 / Rack 4',
    scheduledDate: '2026-09-28',
    createdAt: '2026-09-28T09:30:00Z',
    totalAmount: 345.0,
    paymentStatus: 'paid',
    climateControlled: true,
    qrCodeToken: 'B2B-TOKEN-8922-A41',
  },
  {
    id: 'ord-8923',
    trackingNumber: 'B2B-ES-8923',
    customerName: 'Marta Fernandez',
    customerEmail: 'marta.fdz@outlook.com',
    customerPhone: '+34 633 118 765',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    serviceType: 'smart-locker',
    itemsSummary: '2x Ski Bags, Winter Sports Gear, 1x Hardcase Luggage',
    itemsCount: 3,
    volumeM3: 1.5,
    pickupAddress: 'Smart Locker Station Plaza Colón #08',
    deliveryAddress: 'Box2Box Hub Central Madrid, Locker Bank C',
    status: 'pending_pickup',
    warehouseHub: 'Madrid Central Hub #01',
    warehouseBay: 'Locker #L-204',
    lockerCode: 'LK-9021-COLON',
    scheduledDate: '2026-09-28',
    createdAt: '2026-09-28T11:05:00Z',
    totalAmount: 48.0,
    paymentStatus: 'paid',
    climateControlled: false,
    qrCodeToken: 'B2B-TOKEN-8923-L08',
  },
  {
    id: 'ord-8924',
    trackingNumber: 'B2B-ES-8924',
    customerName: 'Lucas Dubois',
    customerEmail: 'l.dubois@architects.fr',
    customerPhone: '+34 688 223 910',
    customerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    serviceType: 'b2b-vault',
    itemsSummary: '6x Architectural Scale Models, Timber Samples, Plotter Prints',
    itemsCount: 8,
    volumeM3: 6.2,
    pickupAddress: 'Calle Goya 22, 28001 Madrid',
    deliveryAddress: 'Box2Box High-Security Climate Vault #2',
    status: 'stored_in_vault',
    courierAssigned: {
      id: 'cr-03',
      name: 'Mateo Navarro',
      phone: '+34 670 994 112',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
      vehiclePlate: '7112-LNV',
      vehicleType: 'Electric Van',
    },
    warehouseHub: 'Madrid Central Hub #01',
    warehouseBay: 'Vault Zone C-01',
    scheduledDate: '2026-09-27',
    createdAt: '2026-09-27T14:20:00Z',
    totalAmount: 260.0,
    paymentStatus: 'paid',
    climateControlled: true,
    qrCodeToken: 'B2B-TOKEN-8924-V2C',
  },
  {
    id: 'ord-8925',
    trackingNumber: 'B2B-ES-8925',
    customerName: 'Valeria Gomez',
    customerEmail: 'valeria.g@fashionbrand.com',
    customerPhone: '+34 655 771 902',
    customerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    serviceType: 'door-to-door',
    itemsSummary: '18x Seasonal Garment Racks, Mannequins, Pop-up Staging',
    itemsCount: 22,
    volumeM3: 14.5,
    pickupAddress: 'Box2Box Hub Central Madrid, Nave 12',
    deliveryAddress: 'Gran Vía 68, 28013 Madrid',
    status: 'out_for_delivery',
    courierAssigned: {
      id: 'cr-01',
      name: 'Diego Morales',
      phone: '+34 689 112 004',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
      vehiclePlate: '9421-MBB',
      vehicleType: 'Electric Van',
    },
    warehouseHub: 'Madrid Central Hub #01',
    warehouseBay: 'Bay B-09 / Floor',
    scheduledDate: '2026-09-28',
    createdAt: '2026-09-28T07:45:00Z',
    totalAmount: 410.0,
    paymentStatus: 'paid',
    climateControlled: true,
    qrCodeToken: 'B2B-TOKEN-8925-RET',
  },
  {
    id: 'ord-8926',
    trackingNumber: 'B2B-ES-8926',
    customerName: 'Henrik Lindqvist',
    customerEmail: 'henrik@nordicimports.eu',
    customerPhone: '+34 611 392 481',
    customerAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
    serviceType: 'b2b-vault',
    itemsSummary: '35x Crates of High-Precision Lab Equipment',
    itemsCount: 35,
    volumeM3: 22.0,
    pickupAddress: 'Aeropuerto Barajas Cargo Terminal 4',
    deliveryAddress: 'Box2Box Secure Vault Zone A',
    status: 'pending_pickup',
    courierAssigned: {
      id: 'cr-02',
      name: 'Sofia Alva',
      phone: '+34 622 901 883',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
      vehiclePlate: '4091-KTR',
      vehicleType: 'Sprinter Max',
    },
    warehouseHub: 'Madrid Central Hub #01',
    warehouseBay: 'Vault Zone A-08',
    scheduledDate: '2026-09-28',
    createdAt: '2026-09-28T12:00:00Z',
    totalAmount: 780.0,
    paymentStatus: 'pending',
    climateControlled: true,
    qrCodeToken: 'B2B-TOKEN-8926-BAR',
  },
];

export const WAREHOUSE_ZONES: WarehouseZone[] = [
  {
    id: 'zone-a',
    name: 'Climate Vault Zone A',
    code: 'VAULT-A',
    city: 'Madrid',
    totalUnits: 64,
    occupiedUnits: 58,
    capacityM3: 450,
    usedM3: 405,
    temperatureC: 19.4,
    humidityPercent: 44,
    status: 'nominal',
    bays: [
      { id: 'bay-a1', code: 'A-01', rack: 'Rack 1', level: 1, capacityM3: 8, occupiedM3: 8, status: 'occupied', currentOrderId: 'ord-8924', customerName: 'Lucas Dubois', temperatureC: 19.4, humidityPercent: 44 },
      { id: 'bay-a2', code: 'A-02', rack: 'Rack 1', level: 2, capacityM3: 8, occupiedM3: 6.5, status: 'occupied', currentOrderId: 'ord-8812', customerName: 'TechCorp Iberia', temperatureC: 19.3, humidityPercent: 44 },
      { id: 'bay-a3', code: 'A-03', rack: 'Rack 1', level: 3, capacityM3: 8, occupiedM3: 0, status: 'available', temperatureC: 19.4, humidityPercent: 43 },
      { id: 'bay-a4', code: 'A-04', rack: 'Rack 2', level: 1, capacityM3: 10, occupiedM3: 10, status: 'occupied', currentOrderId: 'ord-8790', customerName: 'Gallery Lumina', temperatureC: 19.5, humidityPercent: 45 },
      { id: 'bay-a5', code: 'A-05', rack: 'Rack 2', level: 2, capacityM3: 10, occupiedM3: 0, status: 'reserved', currentOrderId: 'ord-8926', customerName: 'Henrik Lindqvist', temperatureC: 19.4, humidityPercent: 44 },
      { id: 'bay-a6', code: 'A-06', rack: 'Rack 2', level: 3, capacityM3: 10, occupiedM3: 0, status: 'available', temperatureC: 19.2, humidityPercent: 44 },
      { id: 'bay-a7', code: 'A-07', rack: 'Rack 3', level: 1, capacityM3: 12, occupiedM3: 12, status: 'occupied', currentOrderId: 'ord-8651', customerName: 'BioHealth SL', temperatureC: 19.5, humidityPercent: 45 },
      { id: 'bay-a8', code: 'A-08', rack: 'Rack 3', level: 2, capacityM3: 12, occupiedM3: 0, status: 'maintenance', temperatureC: 21.1, humidityPercent: 51 },
    ],
  },
  {
    id: 'zone-b',
    name: 'Standard Pallet & Box Bay Zone B',
    code: 'BAY-B',
    city: 'Madrid',
    totalUnits: 120,
    occupiedUnits: 104,
    capacityM3: 1200,
    usedM3: 1010,
    temperatureC: 21.0,
    humidityPercent: 48,
    status: 'nominal',
    bays: [
      { id: 'bay-b1', code: 'B-01', rack: 'Rack 1', level: 1, capacityM3: 15, occupiedM3: 14.5, status: 'occupied', currentOrderId: 'ord-8921', customerName: 'Elena Rostova', temperatureC: 20.8, humidityPercent: 48 },
      { id: 'bay-b2', code: 'B-02', rack: 'Rack 1', level: 2, capacityM3: 15, occupiedM3: 0, status: 'available', temperatureC: 21.0, humidityPercent: 47 },
      { id: 'bay-b3', code: 'B-03', rack: 'Rack 2', level: 1, capacityM3: 15, occupiedM3: 12.0, status: 'occupied', currentOrderId: 'ord-8922', customerName: 'Carlos Mendonça', temperatureC: 21.2, humidityPercent: 49 },
      { id: 'bay-b4', code: 'B-04', rack: 'Rack 2', level: 2, capacityM3: 15, occupiedM3: 0, status: 'available', temperatureC: 20.9, humidityPercent: 48 },
    ],
  },
  {
    id: 'zone-c',
    name: 'Smart Locker Automated Hub C',
    code: 'LOCKER-C',
    city: 'Madrid',
    totalUnits: 48,
    occupiedUnits: 36,
    capacityM3: 65,
    usedM3: 49,
    temperatureC: 22.1,
    humidityPercent: 46,
    status: 'nominal',
    bays: [
      { id: 'l-01', code: 'L-101', rack: 'Column 1', level: 1, capacityM3: 0.5, occupiedM3: 0.5, status: 'occupied', currentOrderId: 'ord-8923', customerName: 'Marta Fernandez', temperatureC: 22.0, humidityPercent: 46 },
      { id: 'l-02', code: 'L-102', rack: 'Column 1', level: 2, capacityM3: 0.5, occupiedM3: 0, status: 'available', temperatureC: 22.1, humidityPercent: 45 },
      { id: 'l-03', code: 'L-103', rack: 'Column 1', level: 3, capacityM3: 1.0, occupiedM3: 1.0, status: 'occupied', currentOrderId: 'ord-8833', customerName: 'Pedro Almodovar', temperatureC: 22.2, humidityPercent: 46 },
      { id: 'l-04', code: 'L-104', rack: 'Column 2', level: 1, capacityM3: 1.5, occupiedM3: 0, status: 'available', temperatureC: 22.1, humidityPercent: 46 },
    ],
  },
];

export const FLEET_VEHICLES: CourierFleet[] = [
  {
    id: 'fl-01',
    name: 'Diego Morales',
    callsign: 'E-VAN #01 (Alpha)',
    vehicleType: 'Electric Van',
    vehiclePlate: '9421-MBB',
    batteryLevel: 84,
    currentOrders: 4,
    maxCapacityM3: 16.0,
    currentLoadM3: 11.8,
    status: 'active_route',
    currentZone: 'Salamanca District, Madrid',
    speedKmH: 38,
    etaNextStop: '12 mins',
    lastPing: 'Just now',
  },
  {
    id: 'fl-02',
    name: 'Sofia Alva',
    callsign: 'SPRINTER #03 (Bravo)',
    vehicleType: 'Sprinter Max',
    vehiclePlate: '4091-KTR',
    batteryLevel: 92,
    currentOrders: 6,
    maxCapacityM3: 24.0,
    currentLoadM3: 18.5,
    status: 'active_route',
    currentZone: 'Chamberí / Moncloa, Madrid',
    speedKmH: 44,
    etaNextStop: '7 mins',
    lastPing: '2 mins ago',
  },
  {
    id: 'fl-03',
    name: 'Mateo Navarro',
    callsign: 'E-BIKE #07 (Charlie)',
    vehicleType: 'Cargo E-Bike',
    vehiclePlate: 'BIKE-07',
    batteryLevel: 68,
    currentOrders: 2,
    maxCapacityM3: 2.2,
    currentLoadM3: 1.4,
    status: 'active_route',
    currentZone: 'Centro / Sol, Madrid',
    speedKmH: 22,
    etaNextStop: '4 mins',
    lastPing: '1 min ago',
  },
  {
    id: 'fl-04',
    name: 'Javier Ramos',
    callsign: 'E-VAN #04 (Delta)',
    vehicleType: 'Electric Van',
    vehiclePlate: '8832-LPM',
    batteryLevel: 24,
    currentOrders: 0,
    maxCapacityM3: 16.0,
    currentLoadM3: 0,
    status: 'charging',
    currentZone: 'Madrid Central Hub - Fast Charger Bay 2',
    speedKmH: 0,
    etaNextStop: 'Standby',
    lastPing: 'Just now',
  },
];

export const SMART_LOCKERS: SmartLockerBank[] = [
  {
    id: 'lkr-01',
    name: 'Colón Metro Intermodal',
    city: 'Madrid',
    address: 'Plaza de Colón s/n, Estación Metro',
    totalCompartments: 24,
    availableCompartments: 7,
    status: 'online',
    temperatureC: 21.4,
    lastSync: '10s ago',
  },
  {
    id: 'lkr-02',
    name: 'Atocha Central Terminal',
    city: 'Madrid',
    address: 'Glorieta Emperador Carlos V, 28045',
    totalCompartments: 32,
    availableCompartments: 4,
    status: 'online',
    temperatureC: 20.8,
    lastSync: '15s ago',
  },
  {
    id: 'lkr-03',
    name: 'Nuevos Ministerios Business Hub',
    city: 'Madrid',
    address: 'Paseo de la Castellana 67',
    totalCompartments: 28,
    availableCompartments: 12,
    status: 'online',
    temperatureC: 22.0,
    lastSync: '25s ago',
  },
  {
    id: 'lkr-04',
    name: 'Chamartin High-Speed Station',
    city: 'Madrid',
    address: 'Calle de Agustín de Foxá s/n',
    totalCompartments: 24,
    availableCompartments: 9,
    status: 'online',
    temperatureC: 21.1,
    lastSync: '30s ago',
  },
];

export const ACTIVITY_FEED: ActivityEvent[] = [
  {
    id: 'act-1',
    timestamp: '16:08',
    type: 'vault_move',
    title: 'Order B2B-ES-8921 stored in Vault Zone B',
    description: 'Robotic retrieval shuttle loaded 7 items into Rack B-04. Barcode scans verified.',
    actor: 'AGV Shuttle #04',
    badge: 'Vault Stored',
    hub: 'Madrid Central Hub',
  },
  {
    id: 'act-2',
    timestamp: '15:55',
    type: 'pickup',
    title: 'Courier Sofia picked up Order B2B-ES-8922',
    description: '15 boxes secured at Paseo de la Castellana 110. In transit to Hub Nave 14.',
    actor: 'Sofia Alva (Van #03)',
    badge: 'In Transit',
    hub: 'Madrid Central Hub',
  },
  {
    id: 'act-3',
    timestamp: '15:40',
    type: 'locker_deposit',
    title: 'Smart Locker Compartment #L-204 reserved',
    description: 'Client Marta Fernandez generated QR PIN for locker drop-off at Colón Station.',
    actor: 'Self-Service API',
    badge: 'Locker Reserved',
    hub: 'Colón Station Bank',
  },
  {
    id: 'act-4',
    timestamp: '15:20',
    type: 'fleet_dispatch',
    title: 'Courier Diego dispatched for delivery return',
    description: 'Dispatch triggered for Order B2B-ES-8925 to Gran Vía 68 with 18 garment racks.',
    actor: 'Dispatch AI Engine',
    badge: 'Dispatched',
    hub: 'Madrid Central Hub',
  },
  {
    id: 'act-5',
    timestamp: '14:50',
    type: 'alert',
    title: 'Zone A Bay A-08 Climate Sensor recalibration',
    description: 'Humidity reached 51% (target <=45%). Automated dehumidification cycled on.',
    actor: 'HVAC Sensor Node 8',
    badge: 'Auto Cleared',
    hub: 'Vault Zone A',
  },
];

export const REVENUE_SERIES = [
  { label: 'Mon', revenue: 14200, storageM3: 1610, pickups: 42 },
  { label: 'Tue', revenue: 18450, storageM3: 1640, pickups: 55 },
  { label: 'Wed', revenue: 16900, storageM3: 1680, pickups: 49 },
  { label: 'Thu', revenue: 21300, storageM3: 1720, pickups: 68 },
  { label: 'Fri', revenue: 26800, storageM3: 1780, pickups: 84 },
  { label: 'Sat', revenue: 19500, storageM3: 1810, pickups: 51 },
  { label: 'Sun', revenue: 13200, storageM3: 1830, pickups: 33 },
];
